---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
spec:
  secretName: mysql-secrets
  instances: 3
  router:
    instances: 2
  tlsUseSelfSigned: true
  datadirVolumeClaimTemplate:
    storageClassName: non-redundant
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "500Mi"
  podSpec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/managed-by
                  operator: In
                  values:
                    - mysql-operator
            topologyKey: kubernetes.io/hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  # phpMyAdmin session handling is not really compatible with more replicas
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOSTS
              value: mysql-cluster
            - name: PMA_PORTS
              value: 6446,6446,3306,3306,3306
            - name: PMA_ABSOLUTE_URI
              value: https://phpmyadmin.3nk45yqd6e.codemowers.cloud/
            - name: UPLOAD_LIMIT
              value: 10G
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.3nk45yqd6e.codemowers.cloud
spec:
  rules:
  - host: phpmyadmin.3nk45yqd6e.codemowers.cloud
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: phpmyadmin
            port:
              number: 80
  tls:
  - hosts:
    - "*.3nk45yqd6e.codemowers.cloud"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
